### ISSUE TITLE
generateRandomKeys() and generateRandomKeysSync() both throw errors

### ISSUE THREAD

**Issue by thespychief** [juanelas/paillier-bigint#2]
The library is being used in a React application. As per the docs, the library is imported using
`import * as paillierBigint from 'paillier-bigint';`

When `generateRandomKeys()` is called, i.e.
```
async componentDidMount() {
    const { publicKey, privateKey } = await paillierBigint.generateRandomKeys(1024);
}
```

a `ReferenceError` is thrown:
```
ReferenceError: _ref is not defined 3 19ab5d16-dff8-9444-8729-85d98526cdcd:228:7
    onmessage blob:http://localhost:3000/19ab5d16-dff8-9444-8729-85d98526cdcd:228
    (Async: EventHandlerNonNull)
    <anonymous> blob:http://localhost:3000/19ab5d16-dff8-9444-8729-85d98526cdcd:227
    <anonymous> blob:http://localhost:3000/19ab5d16-dff8-9444-8729-85d98526cdcd:229
```

When `generateRandomKeysSync()` is called, i.e.
```
async componentDidMount() {
    const { publicKey, privateKey } = await paillierBigint.generateRandomKeys(1024);
}
```

a `TypeError` is thrown:
```
TypeError: can't convert BigInt to number
_isProbablyPrime
node_modules/bigint-crypto-utils/lib/index.browser.mod.js:792

  789 |   ++a
  790 | }
  791 | 
> 792 | const m = d / (2n ** a)
      | ^  793 | 
  794 | do {
  795 |   const b = randBetween(d, 2n)

primeSync
node_modules/bigint-crypto-utils/lib/index.browser.mod.js:333

  330 |   let rnd = 0n
  331 |   do {
  332 |     rnd = fromBuffer(randBitsSync(bitLength, true))
> 333 |   } while (!_isProbablyPrime(rnd, iterations))
  334 |   return rnd
  335 | }
  336 | 

generateRandomKeysSync
node_modules/paillier-bigint/lib/index.browser.mod.js:178

  175 | let p, q, n, g, lambda, mu
  176 | // if p and q are bitLength/2 long ->  2**(bitLength - 2) <= n < 2**(bitLength)
  177 | do {
> 178 |   p = primeSync(Math.floor(bitlength / 2) + 1)
      | ^  179 |   q = primeSync(Math.floor(bitlength / 2))
  180 |   n = p * q
  181 | } while (q === p || bitLength(n) !== bitlength)

componentDidMount
src/components/Client.jsx:18

  15 |   };
  16 | }
  17 | 
> 18 | componentDidMount() {
     | ^  19 |   console.log('hello client');
  20 |   // console.log(this.state.publicKey);
  21 |   // console.log(this.state.privateKey);
```

**Comment by thespychief** [comment]
I made this one issue instead of two because it seems to me they might be related. It looks like the problem might reside in the `bigint-crypto-utils` library. @juanelas if you'd like help tracking it down I can run through it and see what I can find.

**Comment by juanelas** [comment]
I'm sorry @thespychief I'm not able to reproduce your error. I've tested the methods in React and they're working as expected. I've just created an app with create-react-app (`npx create-react-app my-app`) and replaced `App.js` with the following contents:

```javascript
import React from 'react';
import logo from './logo.svg';
import './App.css';
import * as paillierBigint from 'paillier-bigint'

class App extends React.Component {
  state = {
    publicKey: null,
    privateKey: null
  }
  componentDidMount() {
    paillierBigint.generateRandomKeys(1024).then( keypair => {
      this.setState({
        publicKey: keypair.publicKey,
        privateKey: keypair.privateKey
      })
    })
  }
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Paillier publicKey module: { this.state.publicKey ? this.state.publicKey.n.toString() : 'computing' }.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
            >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;

```
Could you test it yourself? I would say that the actual issue is that your are trying to polyfill the code for older browsers with no bigint support.
Please let me know your feedback. Thanks in advance for contributing!

**Comment by juanelas** [comment]
Well, I've seen the issue when serving a production build. It's probably related to babel not targeted to esnext (bigint is esnext). In order to fix it, you should override babel configuration so that the bundle is properly created. In the case you're using create-react-app, you will need to eject your app (if not already ejected). Hope it helps.

**Comment by juanelas** [comment]
I retract what I said!! You don't need to eject your cra but to properly configure the supported browser list. Since bigint support is pretty new and the library is not thought to be polyfilled (I've got a personal strong position against it when updating the browsers is for free), you should target the latest ones.
Just open your package.json and modify the browserList so that it only targets the latest browsers (supporting the latest features):
```json
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```
I'm sorry I wasn't too familiar with CRA. In any case, I will definitely update the docs of my libraries to avoid unnecessary wasting of time to CRA (or just babel) users.
Please let me know if you've been able to use the library before closing the issue

**Comment by thespychief** [comment]
Excellent, thank you very much; I have been using the library through Node and so far it's been great. Even synchronous key generation for 3072-bit keys takes only a few seconds on my machine. Thank you!
